license="GNUv3"

issueTrackerURL="https://github.com/GamerDuck123/AlwaysAuth/issues"

[[mods]]
modId="alwaysauth"
version="0.4.5"
displayName="AlwaysAuth"
authors="GamerDuck123"
description='''Keep your server always online even when mojang isnt!'''

[[mixins]]
config="alwaysauth.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.alwaysauth]]
    modId="neoforge"
    type="required"
    versionRange="[21.11.38-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alwaysauth]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"
