name: '${name}'
main: '${group}.${mainFile}'

version: '${version}'
description: '${description}'
api-version: '${apiVersion}'

libraries:
  - com.h2database:h2:2.3.232
  - mysql:mysql-connector-java:8.0.33
  - org.mariadb.jdbc:mariadb-java-client:3.3.2

commands:
  alwaysauth:
    description: Manage session fallback system
    usage: /alwaysauth [status|stats|toggle|security|cleanup|reload]
    aliases: [aa, alwaysa]
    permission: alwaysauth.admin

permissions:
  alwaysauth.admin:
    description: Access to all AlwaysAuth commands
    default: op